version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://dbuser:dbpassword@db_service:5432/mydb
    volumes:
      - ./backend/src:/app
    depends_on:
      db_service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db_service:
    image: postgres:15
    container_name: db_service
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: >
        bash -c '
        psql -U dbuser -d mydb -c "SELECT 1" || exit 1
        '
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  postgres_data: